POST http://localhost:5000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

mutation( $title: String!) { 
    addBook(title: $title) {
        id
        title
    }
}

{"title": "buku baru"}

###
POST http://localhost:5000/graphql HTTP/1.1
X-Request-Type: GraphQL
Content-Type: application/json

query {
    books {
        id
        title
    }
}
